package world.ucode.enums;

/**
 * Creature names with their Animations and Sounds
 */
public enum CREATURES_NAMES {
    DARK(FLY_IMAGES.DARK, DIE_IMAGES.DARK, FIRE_IMAGES.DARK, DIE_SOUNDS.DARK, FIRE_SOUNDS.DARK),
    BONE(FLY_IMAGES.BONE, DIE_IMAGES.BONE, FIRE_IMAGES.BONE, DIE_SOUNDS.BONE, FIRE_SOUNDS.BONE),
    FENIX(FLY_IMAGES.FENIX, DIE_IMAGES.FENIX, FIRE_IMAGES.FENIX, DIE_SOUNDS.FENIX, FIRE_SOUNDS.FENIX),
    GHOST(FLY_IMAGES.GHOST, DIE_IMAGES.GHOST, FIRE_IMAGES.GHOST, DIE_SOUNDS.GHOST, FIRE_SOUNDS.GHOST),
    BONE_INVERSED(FLY_IMAGES.BONE_INVERSED, DIE_IMAGES.BONE_INVERSED, FIRE_IMAGES.BONE_INVERSED, DIE_SOUNDS.BONE_INVERSED, FIRE_SOUNDS.BONE_INVERSED),
    GHOST_INVERSED(FLY_IMAGES.GHOST_INVERSED, DIE_IMAGES.GHOST_INVERSED, FIRE_IMAGES.GHOST_INVERSED, DIE_SOUNDS.GHOST_INVERSED, FIRE_SOUNDS.GHOST_INVERSED),
    ARCHANGEL(FLY_IMAGES.ARCHANGEL, DIE_IMAGES.ARCHANGEL, FIRE_IMAGES.ARCHANGEL, DIE_SOUNDS.ARCHANGEL, FIRE_SOUNDS.ARCHANGEL),
    BEHEMOTH(FLY_IMAGES.BEHEMOTH, DIE_IMAGES.BEHEMOTH, FIRE_IMAGES.BEHEMOTH, DIE_SOUNDS.BEHEMOTH, FIRE_SOUNDS.BEHEMOTH),
    CHAMPION(FLY_IMAGES.CHAMPION, DIE_IMAGES.CHAMPION, FIRE_IMAGES.CHAMPION, DIE_SOUNDS.CHAMPION, FIRE_SOUNDS.CHAMPION),
    PEGASUS(FLY_IMAGES.PEGASUS, DIE_IMAGES.PEGASUS, FIRE_IMAGES.PEGASUS, DIE_SOUNDS.PEGASUS, FIRE_SOUNDS.PEGASUS),
    THUNDERBIRD(FLY_IMAGES.THUNDERBIRD, DIE_IMAGES.THUNDERBIRD, FIRE_IMAGES.THUNDERBIRD, DIE_SOUNDS.THUNDERBIRD, FIRE_SOUNDS.THUNDERBIRD),
    TROGLODYTE(FLY_IMAGES.TROGLODYTE, DIE_IMAGES.TROGLODYTE, FIRE_IMAGES.TROGLODYTE, DIE_SOUNDS.TROGLODYTE, FIRE_SOUNDS.TROGLODYTE);

    private final FLY_IMAGES fly_image;
    private final DIE_IMAGES die_image;
    private final FIRE_IMAGES fire_image;
    private final DIE_SOUNDS die_sound;
    private final FIRE_SOUNDS fire_sound;

    private CREATURES_NAMES(FLY_IMAGES fly, DIE_IMAGES die, FIRE_IMAGES fire,
                            DIE_SOUNDS die_sound, FIRE_SOUNDS fire_sound) {
        this.fly_image = fly;
        this.die_image = die;
        this.fire_image = fire;
        this.die_sound = die_sound;
        this.fire_sound = fire_sound;
    }

    public FLY_IMAGES getFly() {
        return fly_image;
    }

    public DIE_IMAGES getDie() {
        return die_image;
    }

    public FIRE_IMAGES getFire() {
        return fire_image;
    }

    public DIE_SOUNDS getDieSound() {
        return die_sound;
    }

    public FIRE_SOUNDS getFireSound() {
        return fire_sound;
    }
}
